site_name: Tad Zeila
theme:
  name: material
  logo: logo/cat_white.png
  text: Noto Serif Medium
  code: Roboto Mono Medium
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

nav:
  # ---------- Home ----------
  - Home: 
    - About me: index.md
    - Note: note.md
  # ---------- Programming ----------
  - Programming:
    - Programming: Programming/programming-language.md
    - C: Programming/c/c.md
    - C++:
      - Giới thiệu:
        - Overview: Programming/cpp/cpp-0-overview.md
        - Install: Programming/cpp/cpp-0-install.md
        - HelloWorld: Programming/cpp/cpp-0-helloworld.md
      - Cơ bản:
        - Data Types: Programming/cpp/cpp-1-datatypes.md
        - Basic Operator: Programming/cpp/cpp-1-basic-operator.md
        - Flow Control: Programming/cpp/cpp-1-flow-control.md
        - Input and Output: Programming/cpp/cpp-1-input-and-output.md
        - Condition & Loop: Programming/cpp/cpp-1-condition-loop.md
        - Command Line Arguments: Programming/cpp/cpp-1-command-line-arguments.md
        - Basic Bit Operator: Programming/cpp/cpp-1-bit-operator.md
        - Namespace: Programming/cpp/cpp-1-namespace.md
        - Define: Programming/cpp/cpp-1-define.md
        - Include: Programming/cpp/cpp-1-include.md
      - Function:
        - Function: Programming/cpp/cpp-2-function.md
        - Lambda: Programming/cpp/cpp-2-lambda.md
        - Function as Parameter: Programming/cpp/cpp-2-function-as-parameter.md
      - Pointer:
        - Pointer: Programming/cpp/cpp-3-pointer.md
        - Smart Pointer: Programming/cpp/cpp-3-smart-pointer.md
        - Raw Pointer: Programming/cpp/cpp-3-raw-pointer.md
        - Memory Model: Programming/cpp/cpp-3-memory-model.md
      - STANDARD LIBRARY STD:
        - Type:
          - std::string: Programming/cpp/cpp-3-std-string.md
        - Function:
          - std::sort: Programming/cpp/cpp-3-std-sort.md
          - std::make_share: Programming/cpp/cpp-3-std-make_share.md
          - std::distance: Programming/cpp/cpp-3-std-distance.md
          - std::hash: Programming/cpp/cpp-3-std-hash.md
          - std::unique: Programming/cpp/cpp-3-std-unique.md
      - Project:
        - Giải bảng Sudoku:  Programming/cpp/cpp-project-solver-sudoku.md
    - C#: Programming/c-sharp/c-sharp.md
    - Java:
      - Overview:
        - Java: Programming/Java/java-introduce.md
        - JDK, JRE và JVM: Programming/Java/java-jdk-jre-jvm.md
        - Install: Programming/Java/java-install.md
        - HelloWorld: Programming/Java/java-helloworld.md
      - Basic:
        - Basic Syntax: Programming/Java/java-basic-synctax.md
        - Datatypes & Variables: Programming/Java/java-basic-datatypes-and-variables.md
    - Javascript: Programming/Javascript/javascript.md
    - Kotlin: Programming/Kotlin/kotlin.md
    - Python: Programming/Python/python.md
    - Rust:
      - Overview:
        - Setup: Programming/Rust/rust-setup.md
        - Document: Programming/Rust/rust-document.md
      - Basic:
        - Variables: Programming/Rust/rust-variables.md
    - PhP: Programming/php/php.md
  # ---------- Non Programming ----------
  - Non Programming:
    - Non Programming: NonProgramming/non-programming-language.md
    - HTML: NonProgramming/html/html.md
    - CSS: NonProgramming/css/css.md
    - Markdown: NonProgramming/Markdown/markdown.md
    - Mermaid:
      - Overview: NonProgramming/Mermaid/mermaid-overview.md
    - PlantUml: NonProgramming/PlantUml/plantuml.md
    - Latex: NonProgramming/LaTex/latex.md
    - Katex: NonProgramming/KaTex/katex.md
  # ---------- Developer ----------
  - Developer:
    - Developer: Developer/dev.md
    - Một số khái niệm:
      - OOP: Developer/dev/dev-oop.md
    - Build Tools:
      - Make: Developer/dev/dev-make.md
    - Yocto:
      - Overview: Developer/Yocto/yocto-overview.md
      - Bitbake: Developer/Yocto/yocto-bitbake.md
    - DataStruct:
      - Overview: Developer/DataStruct/dev-dataStruct-overview.md
    - Algorithm:
      - Overview: Developer/Algorithm/dev-algorithm-overview.md
      - Sorting:
        - About Sort: Developer/Algorithm/dev-algorithm-sort.md
        - Selection Sort: Developer/Algorithm/dev-algorithm-selection-sort.md
        - Bubble Sort: Developer/Algorithm/dev-algorithm-bubble-sort.md
        - Insertion Sort: Developer/Algorithm/dev-algorithm-insertion-sort.md
        - Quick Sort: Developer/Algorithm/dev-algorithm-quick-sort.md
        - Counting Sort: Developer/Algorithm/dev-algorithm-counting-sort.md
      - Hash:
        - FNV1a: Developer/Algorithm/dev-algorithm-hashing-fnv1a.md
    - Design Pattern:
      - Overview: Developer/Design_Pattern/dev-design-pattern-overview.md
    - Third Party:
      - FTXUI:
        - Getting Start: Developer/FTXUI/dev-lib-ftxui.md
      - ROS2: Developer/ROS2/dev-ros2.md
      - AWE:
        - AWE: Developer/AWE/awe.md
        - AWE Core: Developer/AWE/awe-core.md
        - AWE Core OS: Developer/AWE/awe-coreos.md
      - Qt:
        - Overview: Developer/Qt/qt-overview.md
    - Practice:
      - Leetcode:
        - Leetcode 46 - Permutations: Developer/practice/leetcode-44.md
  # ---------- Software ----------
  - Software:
    - Overview: Software/software-overview.md
    - VSCode:
      - Install: Software/VSCode/software-vscode-install.md
      - Settings: Software/VSCode/software-vscode-settings.md
      - Keybindings: Software/VSCode/software-vscode-keybindings.md
      - Snippets: Software/VSCode/software-vscode-snippets.md
    - Android Studio:
      - Overview: Software/AndroidStudio/software-android-studio-overview.md
      - Install: Software/AndroidStudio/software-android-studio-install.md
      - SDK: Software/AndroidStudio/software-android-studio-sdk.md
      - Theme: Software/AndroidStudio/software-android-studio-theme.md
      - Troubleshoot: Software/AndroidStudio/software-android-studio-troubleshoot.md
    - QtCreator:
      - Download: Software/Qt/qt-software-qt-creator.md
    - MSYS2:
      - Overview: Software/msys2/software-msys2-overview.md
      - Install: Software/msys2/software-msys2-install.md
      - Package: Software/msys2/software-msys2-pacman.md
    - Putty: Software/Other/putty.md
    - Sambashare: Software/Other/sambashare.md
    - Thảo luận:
      - IDE & Code Editor: Software/software-paper-ide-code-editor.md
  # ---------- Tools ----------
  - Tools:
    - Tools: Tools/tools.md
    - MKDocs:
      - Getting Start: Tools/MKDocs/mkdocs.md
      - Theme: Tools/MKDocs/mkdocs-theme.md
      - CSS: Tools/MKDocs/mkdocs-css.md
      - Katex: Tools/MKDocs/mkdocs-katex.md
      - Mermaid: Tools/MKDocs/mkdocs-mermaid.md
      - PlantUml: Tools/MKDocs/mkdocs-plantuml.md
      - Markdown Extensions: Tools/MKDocs/mkdocs-markdown-extensions.md
      - Markdown Github Publish: Tools/MKDocs/mkdocs-github-publish.md
    - Version Control:
      - Git:
        - About Git: Tools/Git/git-about.md
        - Install: Tools/Git/git-install.md
        - Git Config: Tools/Git/git-config.md
      - Github:
        - Github Overview: Tools/Github/github-overview.md
        - Github Start: Tools/Github/github-start.md
        - Github Page: Tools/Github/github-page.md
      - Repo:
        - Repo Overview: Tools/Repo/repo-overview.md
  # ---------- Operator System ----------
  - Operator System:
    - OS Overview: OS/os-overview.md
    - Common:
      - File System: OS/os-file-system.md
    - Ubuntu:
      - Overview & Install: OS/Ubuntu/os-ubuntu-family-overview-and-install.md
      - Install: OS/Ubuntu/os-ubuntu-install.md
      - System:
        - Folder Hierarch: OS/Ubuntu/os-ubuntu-system-folder-hierarch.md
        - System File: OS/Ubuntu/os-ubuntu-system-file.md
        - File: OS/Ubuntu/os-ubuntu-file.md
    - Windows:
      - Overview: OS/Windows/os-windows-overview.md
      - Một số lệnh thường dùng: OS/Windows/os-windows-cmd-common-command.md
      - System:
        - Macro PATH: OS/Windows/os-windows-common-path.md
        - Environment Variables: OS/Windows/os-windows-environment-variables.md
        - Startup Process: OS/Windows/os-windows-startup-process.md
        - Run: OS/Windows/os-windows-run.md
        - Service Tag and Manufacture: OS/Windows/os-windows-service-tag-and-manufacture.md
      - Network: OS/Windows/os-windows-network.md
      - Shell:
        - Command Prompt:
          - Getting Start: OS/Windows/os-windows-cmd-getting-start.md
          - Command: OS/Windows/os-windows-cmd-command.md
          - Write Script: OS/Windows/os-windows-cmd-write-scripts.md
        - Power Shell:
          - Getting Start: OS/Windows/os-windows-ps-getting-start.md
      - Custom:
        - Usercmd: OS/Windows/os-windows-custom-usercmd.md
    - Android:
      - Overview: OS/Android/os-android-overview.md
  # ---------- Work ----------
  - Work:
    - MnM:
      - Common:
        - Về MnM: Work/MnM/work-about-mnm.md
        - OSAL: Work/MnM/work-mnm-common-osal.md
      - S201:
        - Overview: Work/MnM/work-s201-overview.md
      - W501:
        - Overview: Work/MnM/work-w501-overview.md
      - Z101:
        - Overview: Work/MnM/work-z101-overview.md
      - S210:
        - Overview: Work/MnM/work-s210-overview.md
      - WSA:
        - Overview: Work/MnM/work-wsa-overview.md
        - Download: Work/MnM/work-wsa-download.md
        - Released: Work/MnM/work-wsa-released.md
        - Use FWDN and HDF: Work/MnM/work-wsa-fwdn-and-hdf.md
        - Build: Work/MnM/work-wsa-build.md
        - Task:
          - Phone Noise Sound: Work/MnM/work-wsa-task-mail-phone-noise.md
          - DAB+: Work/MnM/work-wsa-dab+.md
      - ZX:
        - Overview: Work/MnM/work-zx-overview.md
    - BHMC:
      - About BHMC:  Work/BHMC/work-about-bhmc.md
      - Download:  Work/BHMC/work-bhmc-download.md
    - EVO:
      - Start: Work/EVO/work-evo-start.md
      - FWDN: Work/EVO/work-evo-fwdn.md
  # ---------- Study ----------
  - Study:
    - Overview: Study/overview.md
    - Toán học:
      - Chung:
        - Tổng quan: Study/Math/math-overview.md
        - Tập hợp số: Study/Math/math-phan-so.md
      - Số học:
        - Số học: Study/Math/math-numberic-overview.md
      - Hình học:
        - Hình học cơ bản: Study/Math/math-geometry-overview.md
    - Vật Lý:
      - Overview: Study/Physics/physics-overview.md
    - Hoá học:
      - Overview: Study/Chemistry/chemistry-overview.md
    - Lịch Sử:
      - Overview: Study/History/history-overview.md
    - Tin học:
      - Overview: Study/IT/it-overview.md
    - Triết học:
      - Overview: Study/IT/it-overview.md
    - Nghệ thuật:
      - Overview: Study/IT/it-overview.md
    - Âm nhạc:
      - Overview: Study/IT/it-overview.md
  # ---------- Ngôn Ngữ ----------
  - Ngôn Ngữ:
    - Tiếng Anh:
      - Kiến thức:
        - Từ và Câu: Language/English/language-english-words-and-sentences.md
      - Bài Tập:
        - Reading:
          - An Introduction to Film Sound: Language/English/language-english-an-introduction-to-film-sound.md
  # ---------- Diary ----------
  - Diary:
    - Năm 2025: 
      - Tháng 7: Diary/2025/month-7.md
      - Tháng 6: Diary/2025/month-6.md
  - Project:
    - Pokedex: 
      - README: Project/Pokedex/project-pokedex.md
  # ---------- Sách ----------
  - Sách:
    - Tổng Quan: Book/book-overview.md
    - Review:
      - Book/book-review.md

extra_css:
  - stylesheets/theme.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - scripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dothanhdathp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tad.zeila?locale=vi_VN